Exception in thread "main" java.lang.Error: Error thrown
	at TestThrow.main(Unknown Source)
